### PR TITLE
Bug#249#254

### PR DESCRIPTION
**Pull request by tlopatik**
trstrstrst

### CODE REVIEW

**Comment by tlopatik** [comment]
https://share1.tpondemand.com/entity/249

**Comment by tlopatik** [comment]
https://share1.tpondemand.com/entity/254

**Comment by tlopatik** [comment]
https://lopatiplan.tpondemand.com/entity/254

**Comment by tlopatik** [comment]
https://lopatiplan.tpondemand.com/entity/249

**Review by lopatid — APPROVED** [review]

**Comment by lopatid** [comment]
sadsd

**Pull request merged**
